easy_admin:
    user:
        display_name: true
        display_avatar: false
    formats:
        date: 'd/m/Y'
    entities:
        Asso:
            label: Association
            list:
                title: Association
            class: App\Entity\Association

        User:
            label: Utilisateur
            list:
                title: Liste des utilisateurs     
            class: App\Entity\User
        Users:
            label: Licenciers
            list:
                title: Liste des licenciers     
            class: App\Entity\Users
            
        Activite:
            label: Activites
            list:
                title: Activites
            class: App\Entity\Activites
        
        Events:
            class: App\Entity\Events
            label: Evenements
            list:
                title: Evenements
            
        
        