<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3oFyZ6v\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3oFyZ6v/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3oFyZ6v.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3oFyZ6v\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3oFyZ6v\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3oFyZ6v',
    'container.build_id' => 'f193c061',
    'container.build_time' => 1551778742,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3oFyZ6v');
