<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container32RB8Zl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container32RB8Zl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container32RB8Zl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container32RB8Zl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container32RB8Zl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '32RB8Zl',
    'container.build_id' => 'b3caa0e1',
    'container.build_time' => 1551275609,
], __DIR__.\DIRECTORY_SEPARATOR.'Container32RB8Zl');
