<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLT7fRAY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLT7fRAY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLT7fRAY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLT7fRAY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLT7fRAY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LT7fRAY',
    'container.build_id' => '88dfb1b9',
    'container.build_time' => 1550141849,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLT7fRAY');
